# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stv_project 2.3.4' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stv_project 2.3.4
  pod 'FMDB/standalone'

  target 'stv_project 2.3.4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stv_project 2.3.4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
