# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stv_project 2.5.8' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stv_project 2.5.8
  pod 'Firebase' , '~> 4.0'
  pod 'Firebase/AdMob' , '~> 4.0'
  pod 'Firebase/RemoteConfig' , '~> 4.0'
  pod 'Firebase/Messaging' , '~> 4.0'

  target 'stv_project 2.5.8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stv_project 2.5.8UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
